// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvsgmygtiyrooqvhgruh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2c2dteWd0aXlyb29xdmhncnVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMDU1OTYsImV4cCI6MjA2MTY4MTU5Nn0.BkoYIbOk7DZP2-2HAvcYpura3087Xj-3I_Z4dxenVXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);